---
- hosts: web
  sudo: yes

  tasks:
    - name: yum update
      yum: name=* state=latest

    - name: install libselinux-python
      yum: name=libselinux-python state=latest

    - name: install some indispensable tools
      yum: name={{item}} state=latest
      with_items:
        - vim
        - git

    - name: install apache
      yum: name=httpd state=latest

#    - name: copy httpd.conf to remote
#      copy: src=./conf/httpd.conf dest=/etc/httpd/conf/

    - name: start apache and enabled
      service: name=httpd state=started enabled=yes

    - name: on apache
      action: command /sbin/chkconfig httpd on

    - name: Disable iptables
      action: service name=iptables state=stopped enabled=false

    - name: delete httpd root directory in order to create sim link
      action: file dest=/var/www/html state=absent

#    - name: create html directory
#      file: dest=/vagrant/html owner=vagrant group=vagrant state=directory

    - name: create sim link
      file: src=/vagrant dest=/var/www/html owner=vagrant group=vagrant state=link

    - name: install php packages
      yum: name={{item}} state=latest
      with_items:
        - php
        - php-devel
        - php-mbstring
        - php-mysql
      notify:
        - restart apache

    #- name: copy hello.php
    #  copy: src=./hello.php dest=/var/www/html/hello.php owner=vagrant

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
